# Generated by Django 5.1.2 on 2024-10-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('position', models.CharField(choices=[('developer', 'Backend Developer'), ('designer', 'UI/UX Designer'), ('manager', 'Project Manager')], max_length=50, verbose_name='Position Applied For')),
                ('cv', models.FileField(upload_to='cv/', verbose_name='Upload Resume (PDF)')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Upload Photo')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Application Date')),
            ],
        ),
    ]
