# Generated by Django 5.1.2 on 2024-10-28 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='photo',
        ),
    ]
